<a href="https://colab.research.google.com/github/DasariRishikesh/DSA-and-OOPs-with-Python/blob/main/DSA_and_OOPs_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##DATA STRUCTURES AND ALGORITHMS USING PYTHON PROGRAMMING LANGUAGE 

#1.Recursion problems


Step-1 : Recursive case - the flow

Step-2 : Base Case - the stopping criterion

Step-3 : The unconditional case - the constraint

a. How to find a sum of digits of a positive integer number using recursion

sol : f(n) =  n%10 + f(n/10)

In [ ]:
def sumofdig(n):
  assert n>=0 and int(n) == n,'The number must be positive integer'
  if n==0:          #the base condition
    return 0
  else: 
    return int(n%10) + sumofdig(int(n/10))      #the recursive case

sumofdig(4920202)

19

b. How to calculate power of number using recursion?

sol: f(X^n) = x * f(x^n-1)
if n<0 then f(X^n) = x * f(x^n+1)

In [ ]:
def powerofnum(base, pow):
  assert int(pow) == pow, 'The power(exponent) should be posive and integer'
  if pow==0:
    return 1
  elif pow<0:
    return 1/base * powerofnum(base, pow+1)
  else:
    return base*powerofnum(base, pow-1)

powerofnum(3,-2)


0.1111111111111111

c. Find the greatest common divisor(GCD) of two numbers using recursion.

sol: euclidean algorithm
    gcd(a,b) = a/b => qoefficient= x and remainder = y
    then again b/y until y==0
    Therefore, gcd(a,b) return gcd(b, a mod b)

In [ ]:
def gcd(a,b):
  assert int(a) == a and int(b)==b, 'The number must be posive integers'
  if a<0:
    a=-a
  if b<0:
    b=-b
  if b==0:
    return a
  else:
    return gcd(b, a%b)

gcd(-12,-8)


4

d. How to convert a number from decimal to binary using recursion?

sol: f(n) = n mod 2 + 10 * f(n/2)

In [ ]:
def dectobin(n):
  assert int(n) == n, 'the number must be integer'
  if n/2 == 0:
    return 0
  else:
    return n%2 + 10 * dectobin(int(n/2))

dectobin(101)

1100101

**Additional problems**

In [ ]:
print('Power Solution')


def power(base, exponent):
    if exponent == 0:
        return 1
    return base * power(base, exponent-1)

print(power(2,0)) # 1
print(power(2,2)) # 4
print(power(2,4)) # 16

print("-----------------------------------------------------------------------------------")
print('Factorial Solution')

def factorial(num):
    if num <= 1:
        return 1
    return num * factorial(num-1)


print(factorial(1)) # 1
print(factorial(2)) # 2
print(factorial(4)) # 24
print(factorial(7)) # 5040
print("-----------------------------------------------------------------------------------")
print('productOfArray Solution')

def productOfArray(arr):
    if len(arr) == 0:
        return 1
    return arr[0] * productOfArray(arr[1:])

print(productOfArray([1,2,3])) #6
print(productOfArray([1,2,3,10])) #60
print("-----------------------------------------------------------------------------------")
print('recursiveRange Solution')

def recursiveRange(num):
    if num <= 0:
        return 0
    return num + recursiveRange(num - 1)


print(recursiveRange(6))
print("-----------------------------------------------------------------------------------")
print('fib Solution')

def fib(num):
    if (num < 2):
        return num
    return fib(num - 1) + fib(num - 2)



print(fib(4)) # 3
print(fib(10)) # 55
print(fib(28)) # 317811
print(fib(35)) # 9227465
print("-----------------------------------------------------------------------------------")
print('reverse Solution')


def reverse(strng):
    if len(strng) <= 1:
      return strng
    return strng[len(strng)-1] + reverse(strng[0:len(strng)-1])


print(reverse('python')) # 'nohtyp'
print(reverse('appmillers')) # 'srellimppa'
print("-----------------------------------------------------------------------------------")
print('isPalindrome Solution')


def isPalindrome(strng):
    if len(strng) == 0:
        return True
    if strng[0] != strng[len(strng)-1]:
        return False
    return isPalindrome(strng[1:-1])

print(isPalindrome('awesome')) # false
print(isPalindrome('foobar')) # false
print(isPalindrome('tacocat')) # true
print(isPalindrome('amanaplanacanalpanama')) # true
print(isPalindrome('amanaplanacanalpandemonium')) # false
print("-----------------------------------------------------------------------------------")
print('someRecursive Solution')

def someRecursive(arr, cb):
    if len(arr) == 0:
        return False
    if not(cb(arr[0])):
        return someRecursive(arr[1:], cb)
    return True

def isOdd(num):
    if num%2==0:
        return False
    else:
        return True


print(someRecursive([1,2,3,4], isOdd)) # true
print(someRecursive([4,6,8,9], isOdd)) # true
print(someRecursive([4,6,8], isOdd)) # false
print("-----------------------------------------------------------------------------------")
print('flatten Solution')
def flatten(arr):
    resultArr = []
    for custItem in arr:
        if type(custItem) is list:
            resultArr.extend(flatten(custItem))
        else: 
            resultArr.append(custItem)
    return resultArr 



print(flatten([1, 2, 3, [4, 5]])) # [1, 2, 3, 4, 5]
print(flatten([1, [2, [3, 4], [[5]]]])) # [1, 2, 3, 4, 5]
print(flatten([[1], [2], [3]])) # [1, 2, 3]
print(flatten([[[[1], [[[2]]], [[[[[[[3]]]]]]]]]])) # [1, 2, 3]
print("-----------------------------------------------------------------------------------")
print('capitalizeFirst Solution')

def capitalizeFirst(arr):
    result = []
    if len(arr) == 0:
        return result
    result.append(arr[0][0].upper() + arr[0][1:])
    return result + capitalizeFirst(arr[1:]) 




print(capitalizeFirst(['car', 'taco', 'banana'])) # ['Car','Taco','Banana']
print("-----------------------------------------------------------------------------------")
print('nestedEvenSum Solution')

def nestedEvenSum(obj, sum=0):
    for key in obj:
        if type(obj[key]) is dict:
            sum += nestedEvenSum(obj[key])
        elif type(obj[key]) is int and obj[key]%2==0:
            sum+=obj[key]
    return sum



obj1 = {
  "outer": 2,
  "obj": {
    "inner": 2,
    "otherObj": {
      "superInner": 2,
      "notANumber": True,
      "alsoNotANumber": "yup"
    }
  }
}

obj2 = {
  "a": 2,
  "b": {"b": 2, "bb": {"b": 3, "bb": {"b": 2}}},
  "c": {"c": {"c": 2}, "cc": 'ball', "ccc": 5},
  "d": 1,
  "e": {"e": {"e": 2}, "ee": 'car'}
}

print(nestedEvenSum(obj1)) # 6
print(nestedEvenSum(obj2)) # 10
print("-----------------------------------------------------------------------------------")
print('capitalizeWords Solution')

def capitalizeWords(arr):
    result = []
    if len(arr) == 0:
        return result
    result.append(arr[0].upper())
    return result + capitalizeWords(arr[1:])



words = ['i', 'am', 'learning', 'recursion']
print(capitalizeWords(words)) # ['I', 'AM', 'LEARNING', 'RECURSION']
print("-----------------------------------------------------------------------------------")
print('stringifyNumbers Solution')

def stringifyNumbers(obj):
    newObj = obj
    for key in newObj:
        if type(newObj[key]) is int:
            newObj[key] = str(newObj[key])
        if type(newObj[key]) is dict:
            newObj[key] = stringifyNumbers(newObj[key])
    return newObj



obj = {
  "num": 1,
  "test": [],
  "data": {
    "val": 4,
    "info": {
      "isRight": True,
      "random": 66
    }
  }
}

print(stringifyNumbers(obj))

{'num': '1', 
 'test': [], 
 'data': {'val': '4', 
          'info': {'isRight': True, 'random': '66'}
          }
}
print("-----------------------------------------------------------------------------------")
print('collectStrings Solution')

def collectStrings(obj):
    resultArr = []
    for key in obj:
        if type(obj[key]) is str:
            resultArr.append(obj[key])
        if type(obj[key]) is dict:
            resultArr = resultArr + collectStrings(obj[key])
    return resultArr



obj = {
  "stuff": 'foo',
  "data": {
    "val": {
      "thing": {
        "info": 'bar',
        "moreInfo": {
          "evenMoreInfo": {
            "weMadeIt": 'baz'
          }
        }
      }
    }
  }
}

print(collectStrings(obj)) # ['foo', 'bar', 'baz'])
print("-----------------------------------------------------------------------------------")

Power Solution
1
4
16
-----------------------------------------------------------------------------------
Factorial Solution
1
2
24
5040
-----------------------------------------------------------------------------------
productOfArray Solution
6
60
-----------------------------------------------------------------------------------
recursiveRange Solution
21
-----------------------------------------------------------------------------------
fib Solution
3
55
317811
9227465
-----------------------------------------------------------------------------------
reverse Solution
nohtyp
srellimppa
-----------------------------------------------------------------------------------
isPalindrome Solution
False
False
True
True
False
-----------------------------------------------------------------------------------
someRecursive Solution
True
True
False
-----------------------------------------------------------------------------------
flatten Solution
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3]
[1,

#2. Time complexities and big O notation
Language or metric define the efiiciency of the algorithm.

Run time Notations: Best case, average case and worst case

Types of time complexity:

1.   Big O - less than or equal to the worst case 
2.   Big Omega - at least more than the best case
3.   Big Theta - Bouns within the best and worst cases

Types of the complexity: 


*   Constant time - O(1) [Ex : searching particular element in an array (arr[0])]  
*   Linear time - O(n) [Ex: traversing the whole array]
*   Logarithmic time - O(log N) [Ex : merge sort, binary search, heap sort]
*   Quadratic time - O(N^2) [Ex : Nested loop iterations]
*   Exponential - O(2^n) time complexity grows with the addition to the input [Ex: Fibonacci series using recursion]  

Orders:

O(1) < O(logN) < O(N) < O(NlogN) < O(N^2) < O(2^n) < O(N!)





In [ ]:
# print big number in the array

# Iterative method
def arr(array):                       
  big = array[0]                      #--------------------------o(1)
  for i in range(0, len(array)):      #--------------------------o(n)
    if array[i] > big:                #--------------------------o(1)
      big = array[i]                  #--------------------------o(1)
  print(big)                          #--------------------------o(1)

# Recursive Method:
def arn(array, n):
  if n==1:
    return array[0]
  return max(array[n-1], arn(array,n-1))

a = [1,2,3,5,7,4]                     #--------------------------o(1)
print(arr(a))                         #--------------------------o(1)
print(arn(a,len(a)))



7
None
7


**Interview Questions** 

In [ ]:
#Question1                                                        #O(2n)
def foo(array):
    sum = 0                                                       #--------------------------o(1)
    product = 1                                                   #--------------------------o(1)
    for i in array:                                               #--------------------------o(n)
        sum += i                                                        #--------------------------o(1)
    for i in array:                                               #--------------------------o(n)
        product *= i                                              #--------------------------o(1)
    print("Sum = "+str(sum)+", Product = "+str(product))          #--------------------------o(1)

ar1 = [1,2,3,4]
foo(ar1)

#Question2                                           #O(n^2)

def printPairs(array):
    for i in array:                                 #--------------------------O(n^2)}--| ------------O(n^2+n)=O(n^2)                             
        for j in array:                             #--------------------------o(n-1)}----|
            print(str(i)+","+str(j))                #--------------------------o(1)


#Question3                                          #O(n^2)
def printUnorderedPairs(array):                       
    for i in range(0,len(array)):                   #--------------------------o(n^2)-----|--------------o(n^2+n) =O(n^2)
        for j in range(i+1,len(array)):             #--------------------------o(n)-------|------------------------------------[solved using 1.Counting the iterations and 2.Average work]
            print(array[i] + "," + array[j])        #--------------------------o(1)





#Question4                                                        #O(26) = o(ab)
def printUnorderedPairs(arrayA, arrayB):
    for i in range(len(arrayA)):                                  #--------------------------o(5*4)----|------O(5*4 + 4)
        for j in range(len(arrayB)):                              #--------------------------o(4)------|
            if arrayA[i] < arrayB[j]:                             #--------------------------o(1)
                print(str(arrayA[i]) + "," + str(arrayB[j]))      #--------------------------o(1)

arrayA = [1,2,3,4,5]
arrayB = [2,6,7,8]



#Question5
def printUnorderedPairs(arrayA, arrayB):                          #o(ab)
    for i in range(len(arrayA)):                                  #--------------------------o(a)                                  
        for j in range(len(arrayB)):                              #--------------------------o(b)
            for k in range(0,100000):                             #--------------------------o(1)[As still the 100000 is the constant number]
                print(str(arrayA[i]) + "," + str(arrayB[j]))      #--------------------------o(1)

# printUnorderedPairss(arrayA,arrayB)


#Question6
def reverse(array):                                               #O(N)
    for i in range(0,int(len(array)/2)):                          #--------------------------o(N/2)-->O(N)
        other = len(array)-i-1                                    #--------------------------o(1)
        temp = array[i]                                           #--------------------------o(1)
        array[i] = array[other]                                   #--------------------------o(1)
        array[other] = temp                                       #--------------------------o(1)
    print(array)                                                  #--------------------------o(1)

reverse(arrayA)

#Question8                                  #O(N)

def factorial(n):                                       #o(M)
    if n < 0:                               #---------|
        return -1                           #---------|
    elif n == 0:                            #---------|--------------O(1)
        return 1                            #---------|
    else:                                   #---------|
        return n * factorial(n-1)           #--------------------------o(O(M-1))

print(factorial(3))
                                                                                             # O(M) = O(1) +O(M-1)........
                                                                                             # O(M) = O(1)*N + O(1)


#Question9                                      # time complexity is equal to 2^1 + 2^2 + ........+ 2^n = 2^n+1 -2^1  =~ O(2^n)
def allFib(n):                                  # 
    for i in range(n):                          #--------------------------o(n)
        print(str(i)+":, " + str(fib(i)))

def fib(n):                                     # multipe branch called recursively then tie complexity = Branch^Depth  #O(2^n)
    if n <= 0:                                  # For this problem the time complexity is the changing because the change in the iteration of previous function
        return 0                                # For f(1) - 2^1......f(n) - 2^n
    elif n == 1:
        return 1
    return fib(n-1) + fib(n-2)


allFib(4)

#Question10                   #O(LogN)
def powersOf2(n):                                           # The function calling itself with a half of it
    # print("n:"+str(n))                                    # As we learnt the time complexity is of logarithmic time
    if n < 1:
        return 0
    elif n == 1:
        print(1)
        return 1
    else:
        prev = powersOf2(int(n/2))
        # print("prev:"+str(prev))
        print(prev)
        curr = prev*2
        print(curr)
        return curr

powersOf2(50)

#3. Arrays

In [ ]:
# 1D array

from array import *

# 1. create an array and traverse
print('create an array and traverse')
arr1=array('i', [1,2,3,4,5])                     
arr2 = array('d',[1.2,1.45,122.6,33])       
print(arr2)
print(arr1)
print('-------------------------------------')


# 2. Traverse
print('traverse')
def fun(array):                               
  for i in range(len(array)):
    print(array[i])

fun(arr1)
print('-------------------------------------')


# 3. Accessing through index
print('Accessing through index')
print(arr2[2])
print('-------------------------------------')


# 4. Append through append method()
print('Append through append method()')
arr1.append(7)
print(arr1)
print('-------------------------------------')


# 5. Inserting element in an array
print('Inserting element in an array')
arr1.insert(2,5)                              
print(arr1)
print('-------------------------------------')


# 6. Extend using extend method() in array
print('Extend using extend method() in array')
arr3 = array('i', [11,23,45])
arr1.extend(arr3)
print(arr1)
print('-------------------------------------')


# 7. Add elements from python lists
print('Add elements from python lists')
templist = [88,9,19]
arr2.fromlist(templist)
print(arr2)
print('-------------------------------------')


# 8. Remove element using remove() method
print('Remove element using remove() method')
arr2.remove(9)
print(arr2)
print('-------------------------------------')


# 9. Remove last array element using pop() method 
print('Remove last array element using pop() method')
arr1.pop()
print(arr1)
print('-------------------------------------')


# 10. 
print('Accessing through index')
print('-------------------------------------')


print('Accessing through index')
print('-------------------------------------')


def funs(array, index):                       #accessing array element
  if index>=len(array): 
     return "Enter valid index number"
  else:
    return array[index]
def find(array, value):                       #searching the array
  for i in range(len(array)):
    if i == value:
      return array[i]
  return "The element not found."

def dele(array, n):                            #Delete element in an array
  for i in range(len(array)):
    if i== n:
      array.remove(array[i])
  print(array)
  array.pop() # pop()
  print(array)
  del array[5] # del method 
  print(array)



funs(arr2,4)
find(arr1,5)
dele(arr1,7)

create an array and traverse
array('d', [1.2, 1.45, 122.6, 33.0])
array('i', [1, 2, 3, 4, 5])
-------------------------------------
traverse
1
2
3
4
5
-------------------------------------
Accessing through index
122.6
-------------------------------------
Append through append method()
array('i', [1, 2, 3, 4, 5, 7])
-------------------------------------
Inserting element in an array
array('i', [1, 2, 5, 3, 4, 5, 7])
-------------------------------------
Extend using extend method() in array
array('i', [1, 2, 5, 3, 4, 5, 7, 11, 23, 45])
-------------------------------------
Add elements from python lists
array('d', [1.2, 1.45, 122.6, 33.0, 88.0, 9.0, 19.0])
-------------------------------------
Remove element using remove() method
array('d', [1.2, 1.45, 122.6, 33.0, 88.0, 19.0])
-------------------------------------
Remove last array element using pop() method
array('i', [1, 2, 5, 3, 4, 5, 7, 11, 23])
-------------------------------------
Accessing through index
-----------------------

In [ ]:
from numpy.lib.shape_base import column_stack
## 2D ARRAY

# 1. Create a 2D array
print('creating a 2D array')
print('--------------------------------')

import numpy as np

the2Darray = np.array([[11,23,34,45], [90,89,78,67], [55,11,99,82], [40,92,74,100]])
print(the2Darray)
print('--------------------------------')

# 2. Add new row or Column
print('Adding new row or column')
print('Row Added')
rowaddarray = np.insert(the2Darray,2,[[54,32,21,87]], axis =0)
Arr_add = np.insert(the2Darray,1, [[12,23,34,45]],axis = 0)
print(rowaddarray)
print(Arr_add)

print('Column Added')
Columnarray = np.insert(rowaddarray,0,[[71,92,13,65,96]],axis=1)
print(Columnarray)


print('using append method()')
Columnsarray = np.append(the2Darray,[[1,0,8,6]],axis =0)
print(Columnsarray)
print('-------------------------------')

print('Accessing elements in a 2D array')
def AccessEle(array, Rindex, Cindex):
  if Rindex >= len(array) or Cindex>= len(array[0]):         #-----------O(1)
    return 'Invaid inputs'                                   #-----------O(1)
  return array[Rindex][Cindex]                               #-----------O(1)

print(AccessEle(the2Darray, 2,1))

print('-------------------------------')

print('Travesal of 2D array')
def traverse(array):
  for i in range(len(array)):
    for j in range(len(array[0])):
      print(array[i][j])

traverse(the2Darray)
print('-------------------------------')


print('Searching An element in 2D array')
def searchEle(array, n):
  for i in range(len(array)):
    for j in range(len(array[0])):
      if array[i][j] == n:
        return 'The value is found at ' + str(i) + " "+str(j)
  return 'The elemnent does not exist in the array'

print(searchEle(the2Darray,55))

print('-------------------------------')


print('Deletion of the element from the array(either row deletion or column deletion)')
# Row deletion
NewAFDel = np.delete(the2Darray, 0, axis =0)
print(NewAFDel)

# Column deletion
NewAl = np.delete(the2Darray, 0, axis =1)
print(NewAl)
print('-------------------------------')







creating a 2D array
--------------------------------
[[ 11  23  34  45]
 [ 90  89  78  67]
 [ 55  11  99  82]
 [ 40  92  74 100]]
--------------------------------
Adding new row or column
Row Added
[[ 11  23  34  45]
 [ 90  89  78  67]
 [ 54  32  21  87]
 [ 55  11  99  82]
 [ 40  92  74 100]]
[[ 11  23  34  45]
 [ 12  23  34  45]
 [ 90  89  78  67]
 [ 55  11  99  82]
 [ 40  92  74 100]]
Column Added
[[ 71  11  23  34  45]
 [ 92  90  89  78  67]
 [ 13  54  32  21  87]
 [ 65  55  11  99  82]
 [ 96  40  92  74 100]]
using append method()
[[ 11  23  34  45]
 [ 90  89  78  67]
 [ 55  11  99  82]
 [ 40  92  74 100]
 [  1   0   8   6]]
-------------------------------
Accessing elements in a 2D array
11
-------------------------------
Travesal of 2D array
11
23
34
45
90
89
78
67
55
11
99
82
40
92
74
100
-------------------------------
Searching An element in 2D array
The value is found at 2 0
-------------------------------
Deletion of the element from the array(either row deletion or column d

* Time and space complexities of 2D array.

Operation| Time Comolexity | Space Complexity
--|:--|:--|
Creating an empty array|O(1)|O(mn)
Inserting a column/ row in an array| O(mn)/O(1)| O(1)
Traversing a given array| O(mn)|O(1)
Accessing a given array| O(1)|O(1)
Searching a given value| O(mn)| O(1)
Deleting a given value| O(mn)/O(1)| O(1)

# Python Lists
The list is one among the built-in data types and in python(i.e others are tuples, sets and dictioneries). 
The list is used to store elements in order. The main difference between list and array is they can store different datatypes in a single list but the array cannot.

In [ ]:
# examples of list

integers = [1,2,3,4]                        #list with intergers
print(integers)
stringlist = ['Tarun', 'is', 'going','for','Texas']                 # list of strings
print(stringlist)
mixedlist = [1,3.7, 'heelo']                 # list of mixed datatypes
print(mixedlist)
nestedlist = [1,.44,55,['losst']]            # list inside a list
print(nestedlist)
empty= []                                    # an empty list
print(empty)


###Operations in the lists
print('Operations in the lists')
print('-------------------------')
# Accessing the list
print('Accessing the list')
examplelist = ['Tarun', 'is', 'going','for','Texas']
print(examplelist[4])

#other means for checking or accessing the elements in list is
#using in operator
print('using in operator')
examplelist = ['Tarun', 'is', 'going','for','Texas']
print('for' in examplelist)
#usnig negative index values
print('usnig negative index values')
print(examplelist[-3])
print('--------------------')
#traverse through the list
print('Traverse the list')
for i in examplelist:
  print(i)

# travrsing and adding the list
lists = [1,1,3,4]
for i in range(len(lists)):
  if i>0:
    lists[i] += lists[i-1]
    print(lists)
# Statements passed in empty list cannot print as the empty list cannot be traversed
empty =[]
for i in empty:
  print('List is empty list')

print('-------------------------')


[1, 2, 3, 4]
['Tarun', 'is', 'going', 'for', 'Texas']
[1, 3.7, 'heelo']
[1, 0.44, 55, ['losst']]
[]
Operations in the lists
-------------------------
Accessing the list
Texas
using in operator
True
usnig negative index values
going
--------------------
Traverse the list
Tarun
is
going
for
Texas
[1, 2, 3, 4]
[1, 2, 5, 4]
[1, 2, 5, 9]
-------------------------
Operation and functions in list
Concat using the + operator
[1, 2, 3, 4, 'h', 's', 'f']
print multiple using the * operator
[1, 2, 3, 1, 2, 3]
using len() for count 
6 count of the list k
Using the max() method for get highest value in the list
3
Using the min() method for get lowest value in the list
1
Using the sum() method for adding all items in the list
12
Find Mean
2.0


The list is a mutable datastructure. so we can update with assignment operators or insert new elements into the list.

The insertion acn be done in 4 ways.


1.  Insert at the begining of list
2.  Insert in the middle of the list
3.  Insert at the end of the list
4.  Insert the list to another list

Can be done using the list methods and they are:


*   Insert(Index to insert, value to insert)
*   Append(value to insert at the end)
*   Extend(list to add)





In [ ]:
#Update or Insert the list
Listitems = [1,2,3,4,4,5,6]
Listitems[3] = 12
Listitems[5] = 99 
print(Listitems)

# using the insert()   -------------O(n) space-O(1)
Listitems.insert(4,88)
print(Listitems)

# unig the append() ----------------O(1)
Listitems.append(0)
print(Listitems)

# using the extend()---------------depends on the no. of elemenst in the previous list O(n) and space-O(n)
List = [122,455,667,"Lokesh kanakaraj"]
List.extend(Listitems)
print(List)



[1, 2, 3, 12, 4, 99, 6]
[1, 2, 3, 12, 88, 4, 99, 6]
[1, 2, 3, 12, 88, 4, 99, 6, 0]
[122, 455, 667, 'Lokesh kanakaraj', 1, 2, 3, 12, 88, 4, 99, 6, 0]


* Deletion and slicing in Lists

* List acn be deleted using:


1.   pop() - unless you pass the index the last element is popped from the list and if you pass the element then that indexed element is popped. It is used to know the deleted element. Return popped element.

2.   delete() - use keyword 'del'. Does ot return the deleted element. Uses the index.
3.   remove() - is useful when you know the element itself. Do not need of the index. Provide the value amd delete it 



In [ ]:
List = ['a','b','c','d','e','f']
my = list((3,'avdh',3.78))
print(List)
print(my)
print(List[1:8:2])
List[0:1] = 'q','r'
print(List)

#using the pop()---------------O(1/n)
List.pop()#unless you pass the index the last element is popped from the list and if you pass the element then that indexed element is popped
print(List)

del List[3]
print(List)

#usimg the slice alomg with the del operation---------------O(n)

del List[1:3]
print(List)


# usimg the remove()---------------O(n)
List.remove('q')
print(List)

# space comp;exity for all the elements is O(1)

['a', 'b', 'c', 'd', 'e', 'f']
[3, 'avdh', 3.78]
['b', 'd', 'f']
['q', 'r', 'b', 'c', 'd', 'e', 'f']
['q', 'r', 'b', 'c', 'd', 'e']
['q', 'r', 'b', 'd', 'e']
['q', 'd', 'e']
['d', 'e']


Searching element in list:



1.   IN operator
2.   Linear search



In [ ]:
Thelist = [1,2,3,4,5,6,7,8,9]

#IN-operator
if 10 in Thelist:
  print(Thelist.index(7))#------------O(n) check elements one by one
else:
  print('The value not in the list')


# Linear Search       ---------------O(n)
def search(list, value):
  for i in list:
    if list[i] == value:
      return list.index(value)
  return 'The element not found!'

print(search(Thelist,6))



The value not in the list
5


Operations and functions in List


*   Concat operator (+, join)
*   Multiple operator (*)
*   len() method
*   max() method 
*   min() method
*   sum() method



In [1]:
print("Operation and functions in list")

#concatination in the list using list operations and functions
print("Concat using the + operator")
k = [1,2,3,4]
r= ['h','s','f']
kr = k + r
print(kr)

print("print multiple using the * operator")
k = [1,2,3]
k = k*2
print(k)

print("using len() for count ")
print(len(k),"count of the list k")

print("Using the max() method for get highest value in the list")
print(max(k)) 

print("Using the min() method for get lowest value in the list")
print(min(k))

print("Using the sum() method for adding all items in the list")
print(sum(k))

print("Find Mean")
print(sum(k)/len(k))

Operation and functions in list
Concat using the + operator
[1, 2, 3, 4, 'h', 's', 'f']
print multiple using the * operator
[1, 2, 3, 1, 2, 3]
using len() for count 
6 count of the list k
Using the max() method for get highest value in the list
3
Using the min() method for get lowest value in the list
1
Using the sum() method for adding all items in the list
12
Find Mean
2.0


Pitfalls in list and ways to avoid them:

If we use the below 1 mentioned code then the list returns none that is the 

In [10]:
m =[1,4,3,1,5]
a = 
a =m[:]
m.sort()
print(m)
print(a)

[1, 1, 3, 4, 5]
[1, 4, 3, 1, 5]


#*OBJECT ORIENTED PROGRAMMING IN PYTHON*

1. Instances and classes 
Class is the collection of objects. Prototype by which the obect is created, contains attributes and methods. 

* Attributes and Methods
 Attributes are variables that belongs to class
 
 Method: A function that associated with the class.
 
 objects are instances of the classes and class is a blueprint for creating instances. Instance variables contains data, that is unique to each instance.
    *  State: represented by attributes and reflect prperties.
    *  Behaviour: Represented by methods, reflect response of object on other objects.
    *  Identity: Gives an unique name and enables to interact.

In [11]:
class Employee:
  def __init__(self, employer_name):
    self.employer_name = employer_name

emp_1 = Employee('Hello')
emp_2 = Employee(1)


print(emp_2)

#Other MISC

In [ ]:
#python pickling
List =['I','am','Rishikesh']
print(List)
import pickle
pickle.dump(List,open("save.p",'wb'))

['I', 'am', 'Rishikesh']


In [ ]:
kesa = pickle.load(open("save.p","rb"))
print(kesa)

['I', 'am', 'Rishikesh']


In [ ]:
class risi:
  def statement(self):
    return "Rishikesh"

In [ ]:
from array import *
arr1 = [1,2,3]
arr2 = array('i', [9,8,7,6])
print(arr1)
arr1.pop()
arr1.insert(2,4)
print(arr1)
arr1.append(4)
print(arr1)
arr2.extend(arr1)
arr1.remove(2)
del arr1[0]
print(arr1)
print(arr2)

import numpy as np
array1 = np.array([[1,2,3,4],
                [2,3,4,5],[3,4,5,6]])

column = np.insert(array1,0,[1,2,3,6],axis =0)
print(array1)
print(column)
row = np.delete(array1,2,axis =1)
print(row)

[1, 2, 3]
[1, 2, 4]
[1, 2, 4, 4]
[4, 4]
array('i', [9, 8, 7, 6, 1, 2, 4, 4])
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
[[1 2 3 6]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
[[1 2 4]
 [2 3 5]
 [3 4 6]]


In [ ]:
def fun(string):
  count =0
  list={}
  for i in range(0,len(string)):
    for j in range(i+1,len(string)):
        if string[i] ==string[j]:
              count+=1
              list[i]=string[i]
      
  return list

fun('bharath')

{1: 'h', 2: 'a'}

In [ ]:
from array import *
a = array('i',[1,0,1,0,1,0,2,1,0,0])
def sort_array(array):
  for i in range(len(array)-1):
    temp =array[i+1]
    if array[i+1] < temp:
          temp = array[i]
          array[i] =array[i+1]
          array[i+1] = temp
  return array
print(sort_array(a))


array('i', [1, 0, 1, 0, 1, 0, 2, 1, 0, 0])


In [ ]:

print("FInd mean with use of operations")
list =[]
count = 0
while True:
  inp = input("Enter the number :" )
  if inp == 'Enough': break
  value = int(inp)
  list.append(value)
  count+=1
  avg = sum(list)/len(list)
print(avg,count)

FInd mean with use of operations
Enter the number :1
Enter the number :2
Enter the number :3
Enter the number :4
Enter the number :5
Enter the number :9
Enter the number :8
Enter the number :7
Enter the number :1
Enter the number :9
Enter the number :2
Enter the number :8
Enter the number :7
Enter the number :3
Enter the number :4
Enter the number :6
Enter the number :6
Enter the number :Enough
5.0 17


5