<a href="https://colab.research.google.com/github/DasariRishikesh/DSA-with-Python/blob/main/DSA_with_Python_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##DATA STRUCTURES AND ALGORITHMS USING PYTHON PROGRAMMING LANGUAGE 

#1.Recursion problems


Step-1 : Recursive case - the flow

Step-2 : Base Case - the stopping criterion

Step-3 : The unconditional case - the constraint

a. How to find a sum of digits of a positive integer number using recursion

sol : f(n) =  n%10 + f(n/10)

In [ ]:
def sumofdig(n):
  assert n>=0 and int(n) == n,'The number must be positive integer'
  if n==0:          #the base condition
    return 0
  else: 
    return int(n%10) + sumofdig(int(n/10))      #the recursive case

sumofdig(4920202)

19

b. How to calculate power of number using recursion?

sol: f(X^n) = x * f(x^n-1)
if n<0 then f(X^n) = x * f(x^n+1)

In [ ]:
def powerofnum(base, pow):
  assert int(pow) == pow, 'The power(exponent) should be posive and integer'
  if pow==0:
    return 1
  elif pow<0:
    return 1/base * powerofnum(base, pow+1)
  else:
    return base*powerofnum(base, pow-1)

powerofnum(3,-2)


0.1111111111111111

c. Find the greatest common divisor(GCD) of two numbers using recursion.

sol: euclidean algorithm
    gcd(a,b) = a/b => qoefficient= x and remainder = y
    then again b/y until y==0
    Therefore, gcd(a,b) return gcd(b, a mod b)

In [ ]:
def gcd(a,b):
  assert int(a) == a and int(b)==b, 'The number must be posive integers'
  if a<0:
    a=-a
  if b<0:
    b=-b
  if b==0:
    return a
  else:
    return gcd(b, a%b)

gcd(-12,-8)


4

d. How to convert a number from decimal to binary using recursion?

sol: f(n) = n mod 2 + 10 * f(n/2)

In [ ]:
def dectobin(n):
  assert int(n) == n, 'the number must be integer'
  if n/2 == 0:
    return 0
  else:
    return n%2 + 10 * dectobin(int(n/2))

dectobin(101)

1100101

##### Additional problems

In [ ]:
print('Power Solution')


def power(base, exponent):
    if exponent == 0:
        return 1
    return base * power(base, exponent-1)

print(power(2,0)) # 1
print(power(2,2)) # 4
print(power(2,4)) # 16

print("-----------------------------------------------------------------------------------")
print('Factorial Solution')

def factorial(num):
    if num <= 1:
        return 1
    return num * factorial(num-1)


print(factorial(1)) # 1
print(factorial(2)) # 2
print(factorial(4)) # 24
print(factorial(7)) # 5040
print("-----------------------------------------------------------------------------------")
print('productOfArray Solution')

def productOfArray(arr):
    if len(arr) == 0:
        return 1
    return arr[0] * productOfArray(arr[1:])

print(productOfArray([1,2,3])) #6
print(productOfArray([1,2,3,10])) #60
print("-----------------------------------------------------------------------------------")
print('recursiveRange Solution')

def recursiveRange(num):
    if num <= 0:
        return 0
    return num + recursiveRange(num - 1)


print(recursiveRange(6))
print("-----------------------------------------------------------------------------------")
print('fib Solution')

def fib(num):
    if (num < 2):
        return num
    return fib(num - 1) + fib(num - 2)



print(fib(4)) # 3
print(fib(10)) # 55
print(fib(28)) # 317811
print(fib(35)) # 9227465
print("-----------------------------------------------------------------------------------")
print('reverse Solution')


def reverse(strng):
    if len(strng) <= 1:
      return strng
    return strng[len(strng)-1] + reverse(strng[0:len(strng)-1])


print(reverse('python')) # 'nohtyp'
print(reverse('appmillers')) # 'srellimppa'
print("-----------------------------------------------------------------------------------")
print('isPalindrome Solution')


def isPalindrome(strng):
    if len(strng) == 0:
        return True
    if strng[0] != strng[len(strng)-1]:
        return False
    return isPalindrome(strng[1:-1])

print(isPalindrome('awesome')) # false
print(isPalindrome('foobar')) # false
print(isPalindrome('tacocat')) # true
print(isPalindrome('amanaplanacanalpanama')) # true
print(isPalindrome('amanaplanacanalpandemonium')) # false
print("-----------------------------------------------------------------------------------")
print('someRecursive Solution')

def someRecursive(arr, cb):
    if len(arr) == 0:
        return False
    if not(cb(arr[0])):
        return someRecursive(arr[1:], cb)
    return True

def isOdd(num):
    if num%2==0:
        return False
    else:
        return True


print(someRecursive([1,2,3,4], isOdd)) # true
print(someRecursive([4,6,8,9], isOdd)) # true
print(someRecursive([4,6,8], isOdd)) # false
print("-----------------------------------------------------------------------------------")
print('flatten Solution')
def flatten(arr):
    resultArr = []
    for custItem in arr:
        if type(custItem) is list:
            resultArr.extend(flatten(custItem))
        else: 
            resultArr.append(custItem)
    return resultArr 



print(flatten([1, 2, 3, [4, 5]])) # [1, 2, 3, 4, 5]
print(flatten([1, [2, [3, 4], [[5]]]])) # [1, 2, 3, 4, 5]
print(flatten([[1], [2], [3]])) # [1, 2, 3]
print(flatten([[[[1], [[[2]]], [[[[[[[3]]]]]]]]]])) # [1, 2, 3]
print("-----------------------------------------------------------------------------------")
print('capitalizeFirst Solution')

def capitalizeFirst(arr):
    result = []
    if len(arr) == 0:
        return result
    result.append(arr[0][0].upper() + arr[0][1:])
    return result + capitalizeFirst(arr[1:]) 




print(capitalizeFirst(['car', 'taco', 'banana'])) # ['Car','Taco','Banana']
print("-----------------------------------------------------------------------------------")
print('nestedEvenSum Solution')

def nestedEvenSum(obj, sum=0):
    for key in obj:
        if type(obj[key]) is dict:
            sum += nestedEvenSum(obj[key])
        elif type(obj[key]) is int and obj[key]%2==0:
            sum+=obj[key]
    return sum



obj1 = {
  "outer": 2,
  "obj": {
    "inner": 2,
    "otherObj": {
      "superInner": 2,
      "notANumber": True,
      "alsoNotANumber": "yup"
    }
  }
}

obj2 = {
  "a": 2,
  "b": {"b": 2, "bb": {"b": 3, "bb": {"b": 2}}},
  "c": {"c": {"c": 2}, "cc": 'ball', "ccc": 5},
  "d": 1,
  "e": {"e": {"e": 2}, "ee": 'car'}
}

print(nestedEvenSum(obj1)) # 6
print(nestedEvenSum(obj2)) # 10
print("-----------------------------------------------------------------------------------")
print('capitalizeWords Solution')

def capitalizeWords(arr):
    result = []
    if len(arr) == 0:
        return result
    result.append(arr[0].upper())
    return result + capitalizeWords(arr[1:])



words = ['i', 'am', 'learning', 'recursion']
print(capitalizeWords(words)) # ['I', 'AM', 'LEARNING', 'RECURSION']
print("-----------------------------------------------------------------------------------")
print('stringifyNumbers Solution')

def stringifyNumbers(obj):
    newObj = obj
    for key in newObj:
        if type(newObj[key]) is int:
            newObj[key] = str(newObj[key])
        if type(newObj[key]) is dict:
            newObj[key] = stringifyNumbers(newObj[key])
    return newObj



obj = {
  "num": 1,
  "test": [],
  "data": {
    "val": 4,
    "info": {
      "isRight": True,
      "random": 66
    }
  }
}

print(stringifyNumbers(obj))

{'num': '1', 
 'test': [], 
 'data': {'val': '4', 
          'info': {'isRight': True, 'random': '66'}
          }
}
print("-----------------------------------------------------------------------------------")
print('collectStrings Solution')

def collectStrings(obj):
    resultArr = []
    for key in obj:
        if type(obj[key]) is str:
            resultArr.append(obj[key])
        if type(obj[key]) is dict:
            resultArr = resultArr + collectStrings(obj[key])
    return resultArr



obj = {
  "stuff": 'foo',
  "data": {
    "val": {
      "thing": {
        "info": 'bar',
        "moreInfo": {
          "evenMoreInfo": {
            "weMadeIt": 'baz'
          }
        }
      }
    }
  }
}

print(collectStrings(obj)) # ['foo', 'bar', 'baz'])
print("-----------------------------------------------------------------------------------")

Power Solution
1
4
16
-----------------------------------------------------------------------------------
Factorial Solution
1
2
24
5040
-----------------------------------------------------------------------------------
productOfArray Solution
6
60
-----------------------------------------------------------------------------------
recursiveRange Solution
21
-----------------------------------------------------------------------------------
fib Solution
3
55
317811
9227465
-----------------------------------------------------------------------------------
reverse Solution
nohtyp
srellimppa
-----------------------------------------------------------------------------------
isPalindrome Solution
False
False
True
True
False
-----------------------------------------------------------------------------------
someRecursive Solution
True
True
False
-----------------------------------------------------------------------------------
flatten Solution
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3]
[1,

#2. Time complexities and big O notation
Language or metric define the efiiciency of the algorithm.

Run time Notations: Best case, average case and worst case

Types of time complexity:

1.   Big O - less than or equal to the worst case 
2.   Big Omega - at least more than the best case
3.   Big Theta - Bouns within the best and worst cases

Types of the complexity: 


*   Constant time - O(1) [Ex : searching particular element in an array (arr[0])]  
*   Linear time - O(n) [Ex: traversing the whole array]
*   Logarithmic time - O(log N) [Ex : merge sort, binary search, heap sort]
*   Quadratic time - O(N^2) [Ex : Nested loop iterations]
*   Exponential - O(2^n) time complexity grows with the addition to the input [Ex: Fibonacci series using recursion]  

Orders:

O(1) < O(logN) < O(N) < O(NlogN) < O(N^2) < O(2^n) < O(N!)





In [ ]:
# print big number in the array

# Iterative method
def arr(array):                       
  big = array[0]                      #--------------------------o(1)
  for i in range(0, len(array)):      #--------------------------o(n)
    if array[i] > big:                #--------------------------o(1)
      big = array[i]                  #--------------------------o(1)
  print(big)                          #--------------------------o(1)

# Recursive Method:
def arn(array, n):
  if n==1:
    return array[0]
  return max(array[n-1], arn(array,n-1))

a = [1,2,3,5,7,4]                     #--------------------------o(1)
print(arr(a))                         #--------------------------o(1)
print(arn(a,len(a)))



7
None
7


#####Interview Questions 

In [ ]:
#Question1                                                        #O(2n)
def foo(array):
    sum = 0                                                       #--------------------------o(1)
    product = 1                                                   #--------------------------o(1)
    for i in array:                                               #--------------------------o(n)
        sum += i                                                        #--------------------------o(1)
    for i in array:                                               #--------------------------o(n)
        product *= i                                              #--------------------------o(1)
    print("Sum = "+str(sum)+", Product = "+str(product))          #--------------------------o(1)

ar1 = [1,2,3,4]
foo(ar1)

#Question2                                           #O(n^2)

def printPairs(array):
    for i in array:                                 #--------------------------O(n^2)}--| ------------O(n^2+n)=O(n^2)                             
        for j in array:                             #--------------------------o(n-1)}----|
            print(str(i)+","+str(j))                #--------------------------o(1)


#Question3                                          #O(n^2)
def printUnorderedPairs(array):                       
    for i in range(0,len(array)):                   #--------------------------o(n^2)-----|--------------o(n^2+n) =O(n^2)
        for j in range(i+1,len(array)):             #--------------------------o(n)-------|------------------------------------[solved using 1.Counting the iterations and 2.Average work]
            print(array[i] + "," + array[j])        #--------------------------o(1)





#Question4                                                        #O(26) = o(ab)
def printUnorderedPairs(arrayA, arrayB):
    for i in range(len(arrayA)):                                  #--------------------------o(5*4)----|------O(5*4 + 4)
        for j in range(len(arrayB)):                              #--------------------------o(4)------|
            if arrayA[i] < arrayB[j]:                             #--------------------------o(1)
                print(str(arrayA[i]) + "," + str(arrayB[j]))      #--------------------------o(1)

arrayA = [1,2,3,4,5]
arrayB = [2,6,7,8]



#Question5
def printUnorderedPairs(arrayA, arrayB):                          #o(ab)
    for i in range(len(arrayA)):                                  #--------------------------o(a)                                  
        for j in range(len(arrayB)):                              #--------------------------o(b)
            for k in range(0,100000):                             #--------------------------o(1)[As still the 100000 is the constant number]
                print(str(arrayA[i]) + "," + str(arrayB[j]))      #--------------------------o(1)

# printUnorderedPairss(arrayA,arrayB)


#Question6
def reverse(array):                                               #O(N)
    for i in range(0,int(len(array)/2)):                          #--------------------------o(N/2)-->O(N)
        other = len(array)-i-1                                    #--------------------------o(1)
        temp = array[i]                                           #--------------------------o(1)
        array[i] = array[other]                                   #--------------------------o(1)
        array[other] = temp                                       #--------------------------o(1)
    print(array)                                                  #--------------------------o(1)

reverse(arrayA)

#Question8                                  #O(N)

def factorial(n):                                       #o(M)
    if n < 0:                               #---------|
        return -1                           #---------|
    elif n == 0:                            #---------|--------------O(1)
        return 1                            #---------|
    else:                                   #---------|
        return n * factorial(n-1)           #--------------------------o(O(M-1))

print(factorial(3))
                                                                                             # O(M) = O(1) +O(M-1)........
                                                                                             # O(M) = O(1)*N + O(1)


#Question9                                      # time complexity is equal to 2^1 + 2^2 + ........+ 2^n = 2^n+1 -2^1  =~ O(2^n)
def allFib(n):                                  # 
    for i in range(n):                          #--------------------------o(n)
        print(str(i)+":, " + str(fib(i)))

def fib(n):                                     # multipe branch called recursively then tie complexity = Branch^Depth  #O(2^n)
    if n <= 0:                                  # For this problem the time complexity is the changing because the change in the iteration of previous function
        return 0                                # For f(1) - 2^1......f(n) - 2^n
    elif n == 1:
        return 1
    return fib(n-1) + fib(n-2)


allFib(4)

#Question10                   #O(LogN)
def powersOf2(n):                                           # The function calling itself with a half of it
    # print("n:"+str(n))                                    # As we learnt the time complexity is of logarithmic time
    if n < 1:
        return 0
    elif n == 1:
        print(1)
        return 1
    else:
        prev = powersOf2(int(n/2))
        # print("prev:"+str(prev))
        print(prev)
        curr = prev*2
        print(curr)
        return curr

powersOf2(50)

Sum = 10, Product = 24
[5, 4, 3, 2, 1]
6
0:, 0
1:, 1
2:, 1
3:, 2
1
1
2
2
4
4
8
8
16
16
32


32

#3. Arrays

##### 1D Array

In [ ]:
# 1D array

from array import *

# 1. create an array and traverse
print('create an array and traverse')
arr1=array('i', [1,2,3,4,5])                     
arr2 = array('d',[1.2,1.45,122.6,33])       
print(arr2)
print(arr1)
print('-------------------------------------')


# 2. Traverse
print('traverse')
def fun(array):                               
  for i in range(len(array)):
    print(array[i])

fun(arr1)
print('-------------------------------------')


# 3. Accessing through index
print('Accessing through index')
print(arr2[2])
print('-------------------------------------')


# 4. Append through append method()
print('Append through append method()')
arr1.append(7)
print(arr1)
print('-------------------------------------')


# 5. Inserting element in an array
print('Inserting element in an array')
arr1.insert(2,5)                              
print(arr1)
print('-------------------------------------')


# 6. Extend using extend method() in array
print('Extend using extend method() in array')
arr3 = array('i', [11,23,45])
arr1.extend(arr3)
print(arr1)
print('-------------------------------------')


# 7. Add elements from python lists
print('Add elements from python lists')
templist = [88,9,19]
arr2.fromlist(templist)
print(arr2)
print('-------------------------------------')


# 8. Remove element using remove() method by value
print('Remove element using remove() method by value')
arr2.remove(9)
print(arr2)
print('-------------------------------------')


# 9. Remove last array element using pop() method 
print('Remove last array element using pop() method')
arr1.pop()
print(arr1)
print('-------------------------------------')


# 10. 
print('Accessing through index')
print('-------------------------------------')


def funs(array, index):                       #accessing array element
  if index>=len(array): 
     return "Enter valid index number"
  else:
    return array[index]
def find(array, value):                       #searching the array
  for i in range(len(array)):
    if i == value:
      return array[i]
  return "The element not found."

def dele(array, n):                            #Delete element in an array
  for i in range(len(array)):
    if i== n:
      array.remove(array[i])
  print(array)
  array.pop() # pop()
  print(array)
  del array[5] # del method 
  print(array)



funs(arr2,4)
find(arr1,5)
dele(arr1,7)

create an array and traverse
array('d', [1.2, 1.45, 122.6, 33.0])
array('i', [1, 2, 3, 4, 5])
-------------------------------------
traverse
1
2
3
4
5
-------------------------------------
Accessing through index
122.6
-------------------------------------
Append through append method()
array('i', [1, 2, 3, 4, 5, 7])
-------------------------------------
Inserting element in an array
array('i', [1, 2, 5, 3, 4, 5, 7])
-------------------------------------
Extend using extend method() in array
array('i', [1, 2, 5, 3, 4, 5, 7, 11, 23, 45])
-------------------------------------
Add elements from python lists
array('d', [1.2, 1.45, 122.6, 33.0, 88.0, 9.0, 19.0])
-------------------------------------
Remove element using remove() method by value
array('d', [1.2, 1.45, 122.6, 33.0, 88.0, 19.0])
-------------------------------------
Remove last array element using pop() method
array('i', [1, 2, 5, 3, 4, 5, 7, 11, 23])
-------------------------------------
Accessing through index
--------------

##### 2D Array

In [ ]:
from numpy.lib.shape_base import column_stack
## 2D ARRAY

# 1. Create a 2D array
print('creating a 2D array')
print('--------------------------------')

import numpy as np

the2Darray = np.array([[11,23,34,45], [90,89,78,67], [55,11,99,82], [40,92,74,100]])
print(the2Darray)
print('--------------------------------')

# 2. Add new row or Column
print('Adding new row or column')
print('Row Added')
rowaddarray = np.insert(the2Darray,2,[[54,32,21,87]], axis =0)
Arr_add = np.insert(the2Darray,1, [[12,23,34,45]],axis = 0)
print(rowaddarray)
print(Arr_add)

print('Column Added')
Columnarray = np.insert(rowaddarray,0,[[71,92,13,65,96]],axis=1)
print(Columnarray)


print('using append method()')
Columnsarray = np.append(the2Darray,[[1,0,8,6]],axis =0)
print(Columnsarray)
print('-------------------------------')

print('Accessing elements in a 2D array')
def AccessEle(array, Rindex, Cindex):
  if Rindex >= len(array) or Cindex>= len(array[0]):         #-----------O(1)
    return 'Invaid inputs'                                   #-----------O(1)
  return array[Rindex][Cindex]                               #-----------O(1)

print(AccessEle(the2Darray, 2,1))

print('-------------------------------')

print('Travesal of 2D array')
def traverse(array):
  for i in range(len(array)):
    for j in range(len(array[0])):
      print(array[i][j])

traverse(the2Darray)
print('-------------------------------')


print('Searching An element in 2D array')
def searchEle(array, n):
  for i in range(len(array)):
    for j in range(len(array[0])):
      if array[i][j] == n:
        return 'The value is found at ' + str(i) + " "+str(j)
  return 'The elemnent does not exist in the array'

print(searchEle(the2Darray,55))

print('-------------------------------')


print('Deletion of the element from the array(either row deletion or column deletion)')
# Row deletion
NewAFDel = np.delete(the2Darray, 0, axis =0)
print(NewAFDel)

# Column deletion
NewAl = np.delete(the2Darray, 0, axis =1)
print(NewAl)
print('-------------------------------')







creating a 2D array
--------------------------------
[[ 11  23  34  45]
 [ 90  89  78  67]
 [ 55  11  99  82]
 [ 40  92  74 100]]
--------------------------------
Adding new row or column
Row Added
[[ 11  23  34  45]
 [ 90  89  78  67]
 [ 54  32  21  87]
 [ 55  11  99  82]
 [ 40  92  74 100]]
[[ 11  23  34  45]
 [ 12  23  34  45]
 [ 90  89  78  67]
 [ 55  11  99  82]
 [ 40  92  74 100]]
Column Added
[[ 71  11  23  34  45]
 [ 92  90  89  78  67]
 [ 13  54  32  21  87]
 [ 65  55  11  99  82]
 [ 96  40  92  74 100]]
using append method()
[[ 11  23  34  45]
 [ 90  89  78  67]
 [ 55  11  99  82]
 [ 40  92  74 100]
 [  1   0   8   6]]
-------------------------------
Accessing elements in a 2D array
11
-------------------------------
Travesal of 2D array
11
23
34
45
90
89
78
67
55
11
99
82
40
92
74
100
-------------------------------
Searching An element in 2D array
The value is found at 2 0
-------------------------------
Deletion of the element from the array(either row deletion or column d

##### Time and space complexities of 2D array.

Operation| Time Complexity | Space Complexity
--|:--|:--|
Creating an empty array|O(1)|O(mn)
Inserting a column/ row in an array| O(mn)/O(1)| O(1)
Traversing a given array| O(mn)|O(1)
Accessing a given array| O(1)|O(1)
Searching a given value| O(mn)| O(1)
Deleting a given value| O(mn)/O(1)| O(1)

# Python Lists
The list is one among the built-in data types and in python(i.e others are tuples, sets and dictioneries). 
The list is used to store elements in order. The main difference between list and array is they can store different datatypes in a single list but the array cannot.

In [ ]:
# examples of list

integers = [1,2,3,4]                        #list with intergers
print(integers)
stringlist = ['Tarun', 'is', 'going','for','Texas']                 # list of strings
print(stringlist)
mixedlist = [1,3.7, 'heelo']                 # list of mixed datatypes
print(mixedlist)
nestedlist = [1,.44,55,['losst']]            # list inside a list
print(nestedlist)
empty= []                                    # an empty list
print(empty)


###Operations in the lists
print('Operations in the lists')
print('-------------------------')
# Accessing the list
print('Accessing the list')
examplelist = ['Tarun', 'is', 'going','for','Texas']
print(examplelist[4])

#other means for checking or accessing the elements in list is
#using in operator
print('using in operator')
examplelist = ['Tarun', 'is', 'going','for','Texas']
print('for' in examplelist)
#usnig negative index values
print('usnig negative index values')
print(examplelist[-3])
print('--------------------')
#traverse through the list
print('Traverse the list')
for i in examplelist:
  print(i)

# travrsing and adding the list
lists = [1,1,3,4]
for i in range(len(lists)):
  if i>0:
    lists[i] += lists[i-1]
    print(lists)
# Statements passed in empty list cannot print as the empty list cannot be traversed
empty =[]
for i in empty:
  print('List is empty list')

print('-------------------------')


[1, 2, 3, 4]
['Tarun', 'is', 'going', 'for', 'Texas']
[1, 3.7, 'heelo']
[1, 0.44, 55, ['losst']]
[]
Operations in the lists
-------------------------
Accessing the list
Texas
using in operator
True
usnig negative index values
going
--------------------
Traverse the list
Tarun
is
going
for
Texas
[1, 2, 3, 4]
[1, 2, 5, 4]
[1, 2, 5, 9]
-------------------------
Operation and functions in list
Concat using the + operator
[1, 2, 3, 4, 'h', 's', 'f']
print multiple using the * operator
[1, 2, 3, 1, 2, 3]
using len() for count 
6 count of the list k
Using the max() method for get highest value in the list
3
Using the min() method for get lowest value in the list
1
Using the sum() method for adding all items in the list
12
Find Mean
2.0


The list is a mutable datastructure. so we can update with assignment operators or insert new elements into the list.

##### Insertion

The insertion can be done in 4 ways.


1.  Insert at the begining of list
2.  Insert in the middle of the list
3.  Insert at the end of the list
4.  Insert the list to another list

Can be done using the list methods and they are:


*   Insert(Index to insert, value to insert)
*   Append(value to insert at the end)
*   Extend(list to add)





In [ ]:
#Update or Insert the list
Listitems = [1,2,3,4,4,5,6]
Listitems[3] = 12
Listitems[5] = 99 
print(Listitems)

# using the insert()   -------------O(n) space-O(1)
Listitems.insert(4,88)
print(Listitems)

# unig the append() ----------------O(1)
Listitems.append(0)
print(Listitems)

# using the extend()---------------depends on the no. of elemenst in the previous list O(n) and space-O(n)
List = [122,455,667,"Lokesh kanakaraj"]
List.extend(Listitems)
print(List)



[1, 2, 3, 12, 4, 99, 6]
[1, 2, 3, 12, 88, 4, 99, 6]
[1, 2, 3, 12, 88, 4, 99, 6, 0]
[122, 455, 667, 'Lokesh kanakaraj', 1, 2, 3, 12, 88, 4, 99, 6, 0]


##### Deletion and slicing in Lists

* List acn be deleted using:


1.   pop() - unless you pass the index the last element is popped from the list and if you pass the element then that indexed element is popped. It is used to know the deleted element. Return popped element.

2.   delete() - use keyword 'del'. Does ot return the deleted element. Uses the index.
3.   remove() - is useful when you know the element itself. Do not need of the index. Provide the value amd delete it 



In [ ]:
List = ['a','b','c','d','e','f']
my = list((3,'avdh',3.78))
print(List)
print(my)
print(List[1:8:2])
List[0:1] = 'q','r'
print(List)

#using the pop()---------------O(1/n)
List.pop()#unless you pass the index the last element is popped from the list and if you pass the element then that indexed element is popped
print(List)

del List[3]
print(List)

#usimg the slice alomg with the del operation---------------O(n)

del List[1:3]
print(List)


# usimg the remove()---------------O(n)
List.remove('q')
print(List)

# space comp;exity for all the elements is O(1)

['a', 'b', 'c', 'd', 'e', 'f']
[3, 'avdh', 3.78]
['b', 'd', 'f']
['q', 'r', 'b', 'c', 'd', 'e', 'f']
['q', 'r', 'b', 'c', 'd', 'e']
['q', 'r', 'b', 'd', 'e']
['q', 'd', 'e']
['d', 'e']


##### Searching element in list



1.   IN operator
2.   Linear search



In [ ]:
Thelist = [1,2,3,4,5,6,7,8,9]

#IN-operator
if 10 in Thelist:
  print(Thelist.index(7))#------------O(n) check elements one by one
else:
  print('The value not in the list')


# Linear Search       ---------------O(n)
def search(list, value):
  for i in list:
    if list[i] == value:
      return list.index(value)
  return 'The element not found!'

print(search(Thelist,6))



The value not in the list
5


#####Operations and functions in List


*   Concat operator (+, join)
*   Multiple operator (*)
*   len() method
*   max() method 
*   min() method
*   sum() method



In [ ]:
print("Operation and functions in list")

#concatination in the list using list operations and functions
print("Concat using the + operator")
k = [1,2,3,4]
r= ['h','s','f']
kr = k + r
print(kr)

print("print multiple using the * operator")
k = [1,2,3]
k = k*2
print(k)

print("using len() for count ")
print(len(k),"count of the list k")

print("Using the max() method for get highest value in the list")
print(max(k)) 

print("Using the min() method for get lowest value in the list")
print(min(k))

print("Using the sum() method for adding all items in the list")
print(sum(k))

print("Find Mean")
print(sum(k)/len(k))

Operation and functions in list
Concat using the + operator
[1, 2, 3, 4, 'h', 's', 'f']
print multiple using the * operator
[1, 2, 3, 1, 2, 3]
using len() for count 
6 count of the list k
Using the max() method for get highest value in the list
3
Using the min() method for get lowest value in the list
1
Using the sum() method for adding all items in the list
12
Find Mean
2.0


##### Pitfalls in list and ways to avoid them:

If we use the below 1 mentioned code then the list returns none that is the modification in the list is now allowed.

Read the documentation of the python list [here](https://docs.python.org/)



In [ ]:
m =[1,4,3,1,5]
k = m
a =m[:]
m = m.sort() # Result is None
print(m)
print(a)
print(k)

None
[1, 4, 3, 1, 5]
[1, 1, 3, 4, 5]


#ARRAY vs PYTHON LISTS

Similarities

*   Both data structures are mutable.
*   Both can be indexed and iterated through.
*   They both can be sliced.

Differences
*   Arrays are used for the arithmetic operations so using them are more flexible than the lists.
*   Arrays are used for the one specific data types and cannot use other in them like lists.



In [ ]:
# Arthimetic operatios on the ARRAY and LISTS
import numpy as np

Array = np.array([1,2,3,4,5,6])
List  = [1,2,3,4,5]
print(Array)
print(List)

# Arthimetic operation on the array gives the successful result
print('Arthimetic operation on the array gives the successful result')
print(Array/2)

# Arthimetic operation of list gives the error
print("Gives the error on the operation on lists") 
print(List/2)

[1 2 3 4 5 6]
[1, 2, 3, 4, 5]
Arthimetic operation on the array gives the successful result
[0.5 1.  1.5 2.  2.5 3. ]
Gives the error on the operation on lists


TypeError: ignored

In [ ]:
#Array produce the set of same datatype elements
TArray = np.array([1,2,3,'T'])#adata types are changed to the string even we declare them as the integers
print(TArray)

#List takes any type of data types as arguments
RList = [1,2,3,'R']
print(RList)

['1' '2' '3' 'T']
[1, 2, 3, 'R']


Operation| Time Comolexity | Space Complexity
--|:--|:--|
Creating a list |O(1)|O(n)
Inserting a value in list| O(1)/O(n)| O(1)
Traversing a given list| O(n)|O(1)
Accessing a given cell| O(1)|O(1)
Searching a given value| O(n)| O(1)
Deleting a given value| O(1)/O(n)| O(1)


Here is an example implementation of calculating the averge temperature and number of days above the average temperature.

In [ ]:
def fun():
  lists = []
  inp1 = int(input("How many day's temperature? "))
  for i in range(1,inp1+1):
    inp2 = int(input("Enter "+str(i)+" days' temperature "))
    lists.append(inp2)
  avg = round(sum(lists)/inp1,2)
  count = 0
  for i in lists:
    if i>avg:
      count+=1
  print('\nAverage ='+str(avg),"\n"+str(count)+' day(s) above average')
fun()
      

How many day's temperature? 1
Enter 1 days' temperature 5

Average =5.0 
0 day(s) above average


Calculate the missing element from the list

In [ ]:
lists = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100]
def fun(lists,n):
  sum1 = 100*101/2
  sum2 = sum(lists)
  print(sum1-sum2)
fun(lists,100)


50.0


# Dictionaries

The dictionary is the coleection of unordered, changeble and indexed.

It represented using the 'Key' and 'Value'.


#####Creating A dictionary

In [ ]:
dictionary = {"rishi": 35,"Soma": 25, "subbu" : 45}   # cannot use the dupicate keys
print(dictionary)

# use dict method
my_dict = dict()
print(my_dict)

# Access 
dictionary["Soma"] # using the key values


{'rishi': 35, 'Soma': 25, 'subbu': 45}
{}


25

  The key is taken as input to generte the index with the hash value by hash function and returns the ouput as the key value pair in a meomroy index.


For example we have the dictionary as 

my_dictionary = {"Rishi": 35, "Soma" : 25, "Subbu" : 45, "Kasha",: 55}

now lets see how they are stored in the memory, 
For first storing the initial key

Rishi-> hashfun() --- hash value(2171728)----array index = 3

Soma-> hashfun() --- hash value (2171781)----array index = 1

Subbu-> hashfun() --- hash value(2181928)----array index = 2

Kasha-> hashfun() --- hash value(1781928)----array index = 0

Index| Memory Space 
--|:--|
0 |Kasha 55
1| Soma 25
2| Subbu 45
3| Rishi 35

Sometimes the value directs to the index that already occupied then the key-value pair is stored as the Linked list to the other key-value pair.

##### Update and Insert Elements

In [ ]:
#Update or Insert an element in a Dictionary

#update
DIct = {'employee': 'Michel', 'ID': 7, "Department": "Science Engineer"}
print(DIct)
DIct["Department"] = "Associate Engineer"
print(DIct)
# Time complexity : O(1)
# Space Compexity : O(1)


#ADD ELEMENT ( check where it exist to update but the Emp iD is not in "DIct" so it  ADD as another Key value pair)
DIct["Emp ID"] = 1234
print(DIct)
# Time complexity : O(1)
# Space Complexity : amortized O(1)
# Gernerally it is O(1) but changes to o(n) when the underlying DS needs to grow orshrink. It happens indfrequently so named as amoritzed

{'employee': 'Michel', 'ID': 7, 'Department': 'Science Engineer'}
{'employee': 'Michel', 'ID': 7, 'Department': 'Associate Engineer'}
{'employee': 'Michel', 'ID': 7, 'Department': 'Associate Engineer', 'Emp ID': 1234}


#####Traverse through the dictionary

In [ ]:
DIct = {'employee': 'Michel', 'ID': 7, "Department": "Science Engineer","Emp ID": 1234}

def traverse(dicts):      #time Complexity : O(n) as per for loop # Space Complexity : O(1)
  for key in dicts:
    print(key, dicts[key])

traverse(DIct)


employee Michel
ID 7
Department Science Engineer
Emp ID 1234


#####Search inside the dictionary

In [ ]:

# Linear Search
DIct = {'employee': 'Michel', 'ID': 7, "Department": "Science Engineer","Emp ID": 1234, "slary": 25000}

def searchfun(dicts, value): # time Complexity : O(n) # Space complexity : O(1)
  for key in dicts:
    if dicts[key] == value:
      return key, value
  return "No such value found for keys"  

print(searchfun(DIct, 0))
print(searchfun(DIct, 1234))

No such value found for keys
('Emp ID', 1234)


#####Delete or Remove element for dictionary

Time complexity : O(1)

Worst Time complexity :  Amortized O(n)

Space Complexity : O(1)

In [ ]:
# POP() method
print(DIct.pop('ID'))  # returns the value of the respective key
print(DIct)

# popitem() method
# Used to remove and return an arbitary item from the dictionary
#Doesn't take an parameter, returns the key and value pair
print(DIct.popitem()) # deletes any item from the dictionary randomly
print(DIct)


# using the "del"  any particular ite, from the dictionary
del DIct['employee'] 
# if we want to delete entire dictionary using "del" then we no need to wriet any keyword specifically after deleting we can't print the dictionary it gives an error
print(DIct)




# Clear() Method
# Delete all the elements from the dictioanry.
DIct.clear() 

print(DIct)

7
{'employee': 'Michel', 'Department': 'Science Engineer', 'Emp ID': 1234, 'slary': 25000}
('slary', 25000)
{'employee': 'Michel', 'Department': 'Science Engineer', 'Emp ID': 1234}
{'Department': 'Science Engineer', 'Emp ID': 1234}
{}


#####Dictionary Methods

* Clear() - dict.clear() -Doesn't take any parameter or return any value
* Copy() - dict.copy() - creates a new dictioanry and fill the values with values of dict and return the shell copy of dict
*  fromkeys() - dictioanry.fromkeys(sequence[], value) - creates a new dictionary and store the sequence list  as keys and values in the respective sequences, sequences are mandatory where as the values are not.  

* get() - dictionary,get(key, value) - used to retrive the value of the respective key from the dictionary

* items() - dictionary.items() - used for getting the key value pairs as tuples in a list

* keys() - dictionary.keys() - returns the list of keys

* values() - dictionary.values() - returns the list of values in key value pair

popitem() - dictionary.popitem() - deletes any key values pair form the list



In [ ]:
dicts = dict()
dicts["Hello"] = "Good Morning"
dicts['Rishikesh'] = "is The speaker"
dicts["Are"] = "you awake?"
print(dicts)


#copy method()
cts = dicts.copy()
print(cts)

#clear method()
dicts.clear()
print(dicts)

#fromkeys method(sequence(keys)[], Value)
new = {}.fromkeys([1,2,3,4], "kudos")
print(new)


# Get method(key, value)
cts.get("Rishikesh", 3) # return the value of key if key exists in the dictioanry else return the value if specified any!

# Items method()
print(cts.items()) # return the list tuples of key value pairs
 
# Keys method()
print(cts.keys()) # return the Keys in list

# Value method()
print(cts.values())

# popitem method ()
cts.popitem() # delete any key value pair from the dictionary
print(cts)

# Setdefault method()
cts.setdefault("First","Kirrak") # Value and key will be added to dictionary
print(cts)
print(cts.setdefault("Hello", 23)) # returns the correct value from the list is key exists
print(cts)
#using setdefault() if value doesn't specified then return the return the "none"

# pop method(key, value(optioanl))
print(cts.pop("i", 31))
print(cts.pop("Hello"))
# deletes the value key pair if key exists else return the value if specified or "None" by default

# update method(other dictionary)
cts.update(new)
print(cts)

{'Hello': 'Good Morning', 'Rishikesh': 'is The speaker', 'Are': 'you awake?'}
{'Hello': 'Good Morning', 'Rishikesh': 'is The speaker', 'Are': 'you awake?'}
{}
{1: 'kudos', 2: 'kudos', 3: 'kudos', 4: 'kudos'}
dict_items([('Hello', 'Good Morning'), ('Rishikesh', 'is The speaker'), ('Are', 'you awake?')])
dict_keys(['Hello', 'Rishikesh', 'Are'])
dict_values(['Good Morning', 'is The speaker', 'you awake?'])
{'Hello': 'Good Morning', 'Rishikesh': 'is The speaker'}
{'Hello': 'Good Morning', 'Rishikesh': 'is The speaker', 'First': 'Kirrak'}
Good Morning
{'Hello': 'Good Morning', 'Rishikesh': 'is The speaker', 'First': 'Kirrak'}
31
Good Morning
{'Rishikesh': 'is The speaker', 'First': 'Kirrak', 1: 'kudos', 2: 'kudos', 3: 'kudos', 4: 'kudos'}


#####Dictinary operations and Built in functions

* in operator - (key 'in' dictonary) - check the key is in dict or not. If yes returns "true" else "False". Also if we want values we can use ".values()" method

* for operator - (for "keys" in dictionary) traverse through all the elements.

* all () - all(dictionary) -

Cases| Return Value 
--|:--|
All the values are ture| TRUE
All the values are false| FALSE
One value is the true others are false| FALSE
One value is false others are true| FALSE
Empty Iterable| TRUE


* any() - any(dictionary) - 

Cases| Return Value 
--|:--|
All the values are ture| TRUE
All the values are false| FALSE
One value is the true others are false| TRUE
One value is false others are true| TRUE
Empty Iterable| FALSE
 
* len() - len(dictioanry) - number of items in sequence

* sorted() - sorted(dictionary) - sort the dictionary with the keys(if string then return the ascii order) and return the list of sorted keys

In [ ]:
dicts = {"Name": "Rishikesh D","Salary": 76000, "ROll NO": "19bcs035","Branch": "CSE"}

# in operator
print("Saary" in dicts)
print("Name" in dicts)
print(76000 in dicts.values())  #} time complexity - O(n)

# for operator
for keys in dicts:
  print(keys, dicts[keys]) # time complexity - O(n)
  
# all()
mylist = {0:"True", 1:"False",2:"False", 3:"False"}
print(all(mylist))

Us = {0:False,1:False,2:False}
print(all(Us))

kill = {1:"True", 2:"True",3:"True",4:"True"}
print(all(kill))

isl = {0:True,1: True, 2: False, 3: True}
print(all(isl))

ur = {}
print(all(ur))

# any ()

print(any(ur))
print(any(mylist))

# len()
print(len(dicts))

# sorted()
print(sorted(dicts, key = len))


False
True
True
Name Rishikesh D
Salary 76000
ROll NO 19bcs035
Branch CSE
False
False
True
False
True
False
True
4
['Name', 'Salary', 'Branch', 'ROll NO']


##### Dictionary vs Lists

Dictionary| Lists 
--|:--|
Unordered| Ordered
Access via keys| Access via index
Collection of key value pairs| Collection of elements
Preferred when you have unique key values | Preferred when you have the ordered data
No duplicate members| Allow the duplicate

##### Dictionaries Time and Space Complexity

Operation| Time Complexity | Space Complexity
--|:--|:--|
Creating a dictionary|O(len(dictionary)|O(n)
Inserting a value in a dictionary| O(1)/O(n)| O(1)
Traversing a given dictionary| O(n)|O(1)
Accessing a given cell| O(1)|O(1)
Searching a given value| O(n)| O(1)
Deleting a given value| O(1)| O(1)

# Tuples

Tuples are immutable sequence of python objects that can be comparable and hashable

##### Tuple creation

Time complexity  - O(1) and Space Complexity - O(n)

In [ ]:
tup = ("a","e","i","o","u")
print(tup)

t = ("r") #("r",)
print(t)

r = tuple('122334') # allows the dupicates
print(r)

# 

('a', 'e', 'i', 'o', 'u')
r
('1', '2', '2', '3', '3', '4')


##### Tuples in Memory/ Accessing an element of tuple

They are stored in an ordered way in an contiguous manner which also increases the performance of tuple while accessing the elements. 

Main difference between the list and tuples is Tuples are immutable as we cannot change the elemnts once declared.

In [ ]:
tuples = ("a","e","i","o","u")
# Access the elements

#using the indices
print(tuples[2])
print(tuples[-1])

# using the slice operator"[:]"
print(tuples[::-1])
# as change from list is we cannot modify the elements just like list 
for i in tuples:
  print(i)             # Time Complexity  - O(n) and Space Compexity - O(1)
  
# Traverse a tuple
print("-------------------------")
for i in range(len(tuples)):
  print(tuples[i])

i
u
('u', 'o', 'i', 'e', 'a')
a
e
i
o
u
-------------------------
a
e
i
o
u


##### Searching element in tuple


In [ ]:
tu = ('5',2,4,'r','t','6',32,'r')
print("Using 'in' operator")
print('4' in tu) # TIme complexity is O(n)


print("Using index method")     # time complexity is O(1)
print(tu.index(2))

print("Using the linear search")
def fun(s, target):
  for i in range(len(s)):      # Time complexity is O(n)
    if s[i] == target:
      print(f"THE INDEX IS {i}")
      return s.index(s[i])
  return f"Index not found!" 
fun(tu, 'r')

Using 'in' operator
False
Using index method
1
Using the linear search
THE INDEX IS 3
2


##### Operations in tuple

In [ ]:
# Using "+" operator concat two tuples
tup = ('Hi','Good','Morning.')
le = ('Have','a','great','Monday!')
print(tup+le)

# using the "*" operator
# "*" is used for the printing the same tuple or list multiple times
print(tup*4)

# using "in" operator for searching the element
print('a'in tup+le)

# using the "count" for get the counts of an element
print(le.count('a'))

# using the "index" for returning the index of the specific element
print(tup.index('Hi'))
# using the "len" for having the length of the tuple
print(len(tup+le*3))
#using the "max" and "min" method
print(max(tup+le))
print(min(tup))
#it check the ascii values

# Using the tuple method
print(tuple('17189u717'))

('Hi', 'Good', 'Morning.', 'Have', 'a', 'great', 'Monday!')
('Hi', 'Good', 'Morning.', 'Hi', 'Good', 'Morning.', 'Hi', 'Good', 'Morning.', 'Hi', 'Good', 'Morning.')
True
1
0
15
great
Good
('1', '7', '1', '8', '9', 'u', '7', '1', '7')


##### List vs Tuple

* List are mutable, i.e., we can change the lists elements(add, delete, sort, reverse,etc)
Bu the tuples are immutable , we cannot change the elements in the tuples. So we cannot perform the operations such as insertion, change, delete on single elements.

* Tuples use the following functions same as the lists
    * len(), max(), min(), sum(), any(), all(), sorted()
* Methods that are Not used in tuples are
    * append(), insert(), remove(), pop(), clear(), sort(), reverse()
* Tuples can be stored in lists and Lists cambe stored in tuples.
* Tuples and lists can be Nested

Tuples | Lists|
----|: ----|
Immutable | Mutable
Cannot be modified | Can be modified
'( )' are used to represent | '[ ]' are used to represent
Is generaalu used for homogenous datatypes (similar) | Is generally used for Non homogeneous datatypes(Different)
More faster iterable than lists (Static nature) | Slower as compared to tuples(Dynamic Nature)

* As tuple has immutable elements used for the key in dictionary
* If you have data that doesn't change, tuples are most suggested to use for the data protection.

##### Tuples time and space complexities
Operation | Time Complexity | Space Complexity
---|: ---|: ---|
Creating a tuple| O(1) | O(n)
Traverse a given tuple|O(n) | O(1)
Accessing a given element| O(1)| O(1)
Searching a given element| O(n) | O(1)


 


#*OBJECT ORIENTED PROGRAMMING IN PYTHON*

1. Instances and classes 
Class is the collection of objects. Prototype by which the obect is created, contains attributes and methods. 

* Attributes and Methods
 Attributes are variables that belongs to class
 
 Method: A function that associated with the class.
 
 objects are instances of the classes and class is a blueprint for creating instances. Instance variables contains data, that is unique to each instance.
    *  State: represented by attributes and reflect prperties.
    *  Behaviour: Represented by methods, reflect response of object on other objects.
    *  Identity: Gives an unique name and enables to interact.

In [ ]:
class Employee:
  def __init__(self, employer_name):
    self.employer_name = employer_name

emp_1 = Employee('Hello')
emp_2 = Employee(1)


print(emp_2)

#Other MISC

In [ ]:
#python pickling
List =['I','am','Rishikesh']
print(List)
import pickle
pickle.dump(List,open("save.p",'wb'))

['I', 'am', 'Rishikesh']


In [ ]:
kesa = pickle.load(open("save.p","rb"))
print(kesa)

['I', 'am', 'Rishikesh']


In [ ]:
class risi:
  def statement(self):
    return "Rishikesh"

In [ ]:
from array import *
arr1 = [1,2,3]
arr2 = array('i', [9,8,7,6])
print(arr1)
arr1.pop()
arr1.insert(2,4)
print(arr1)
arr1.append(4)
print(arr1)
arr2.extend(arr1)
arr1.remove(2)
del arr1[0]
print(arr1)
print(arr2)

import numpy as np
array1 = np.array([[1,2,3,4],
                [2,3,4,5],[3,4,5,6]])

column = np.insert(array1,0,[1,2,3,6],axis =0)
print(array1)
print(column)
row = np.delete(array1,2,axis =1)
print(row)

[1, 2, 3]
[1, 2, 4]
[1, 2, 4, 4]
[4, 4]
array('i', [9, 8, 7, 6, 1, 2, 4, 4])
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
[[1 2 3 6]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
[[1 2 4]
 [2 3 5]
 [3 4 6]]


In [ ]:
def fun(string):
  count =0
  list={}
  for i in range(0,len(string)):
    for j in range(i+1,len(string)):
        if string[i] ==string[j]:
              count+=1
              list[i]=string[i]
      
  return list

fun('bharath')

{1: 'h', 2: 'a'}

In [ ]:
from array import *
a = array('i',[1,0,1,0,1,0,2,1,0,0])
def sort_array(array):
  for i in range(len(array)-1):
    temp =array[i+1]
    if array[i+1] < temp:
          temp = array[i]
          array[i] =array[i+1]
          array[i+1] = temp
  return array
print(sort_array(a))


array('i', [1, 0, 1, 0, 1, 0, 2, 1, 0, 0])


In [ ]:

print("FInd mean with use of operations")
list =[]
count = 0
while True:
  inp = input("Enter the number :" )
  if inp == 'Enough': break
  value = int(inp)
  list.append(value)
  count+=1
  avg = sum(list)/len(list)
print(avg,count)

FInd mean with use of operations
Enter the number :1
Enter the number :2
Enter the number :3
Enter the number :4
Enter the number :5
Enter the number :9
Enter the number :8
Enter the number :7
Enter the number :1
Enter the number :9
Enter the number :2
Enter the number :8
Enter the number :7
Enter the number :3
Enter the number :4
Enter the number :6
Enter the number :6
Enter the number :Enough
5.0 17


In [ ]:
arr = [1, 2, 3, 4, 5, 6]
for i in range(1, 6):
    arr[i - 1] = arr[i]
for i in range(0, 6): 
    print(arr[i], end = " ")

2 3 4 5 6 6 

In [ ]:
arr = [[1, 2, 3, 4],
       [4, 5, 6, 7],
       [8, 9, 10, 11],
       [12, 13, 14, 15]]
for i in range(0, 4):
    print(arr[i].pop())

4
7
11
15


In [ ]:
a=[1,2,3,4,5,6,7,8,9]
a[::2]=10,20,30,40,50
print(a)

[10, 2, 20, 4, 30, 6, 40, 8, 50]


In [ ]:
a=[1,2,3,4,5,6,7,8,9]
print(a[::2])

[1, 3, 5, 7, 9]


In [ ]:
data = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
def fun(m):
    v = m[0][0]
 
    for row in m:
        for element in row:
            if v < element: v = element
 
    return v
print(fun(data[0]))


4


In [ ]:
def f(value, values):
    v = 1
    values[0] = 44
t = 3
v = [1, 2, 3]
f(t, v)
print(t, v[0])

3 44


In [ ]:
fruit_list1 = ['Apple', 'Berry', 'Cherry', 'Papaya']
fruit_list2 = fruit_list1
fruit_list3 = fruit_list1[:]
fruit_list2[0] = 'Guava'
fruit_list3[1] = 'Kiwi'
 
sum = 0
for ls in (fruit_list1, fruit_list2, fruit_list3):
    if ls[0] == 'Guava':
        sum += 1
    if ls[1] == 'Kiwi':
        sum += 20
 
print(sum)

22


In [ ]:
a=[1,2,3,4,5]
print(a[3:0:-1])


[4, 3, 2]


In [ ]:
s = "Hi I am Rishikesh and I came here" # Reverse the string without changing the words
print(s)
s = s.split()
print(s)
s = s[::-1]
print(s)
s = " ".join(s)
print(s)

Hi I am Rishikesh and I came here
['Hi', 'I', 'am', 'Rishikesh', 'and', 'I', 'came', 'here']
['here', 'came', 'I', 'and', 'Rishikesh', 'am', 'I', 'Hi']
here came I and Rishikesh am I Hi


In [ ]:
class Linked:
  def __init__(self, dataval= None):
    self.dataval = dataval
    self.nextval = None

class node:
  def __init__(self):
    self.headval = None

  def printNode(self):
    printnode = self.headval
    while printnode is not None:
      print(printnode.dataval)
      printnode = printnode.nextval
 
  def InsertNode(self,Newdata):
    NewNode = node(Newdata)

  NewNode.




node1 = node()
node1.headval = Linked('Hii')
n2 = Linked('I am')
n3 = Linked('Rishikesh')

node1.headval.nextval = n2
n2.nextval = n3
node1.printNode()

Hii
I am
Rishikesh


In [ ]:
# Two Sum Leetcode 
array = [1,2,3,4,5,7,4,10]
def find_pairs(arr, target):
  for i in range(len(arr)):
    for j in range(i+1, len(arr)):
      if arr[i] == arr[j]:
        continue
      elif arr[i] + arr[j] == target:
        return i+1,j+1
print(find_pairs(array,7))

  





(2, 5)
